export const additionalInsured = [
"AMERA SOLUTIONS", 
"FLAGSHIP RESORT",
"VEYO LLC",
"SUSSEX COUNTY REGIONAL COOP",
"AMERICAN LOGISTICS COMPANY, LLC",
"MODIVCARE SOLUTIONS LLC",
"ALLY FINANICAL",
"MODIVCARE SOLUTIONS AND DMAHS",
"SUSSEX COUNTY REGIONAL TRANSPORTATION COOPERATIVE",
"FACILITATING ACCESS TO COORDINATION TRANSPORTATION",
"AMERICAN LOGISTICS CO LLC",
"PRIORITY TRANSPORTATION SERVICES",
"ORTEGA LUIS",
"CITY OF FRESNO - BUSINESS TAX/PERMITS",
"NEW JERSEY DEPARTMENT OF HEALTH",
"None"

]

export default additionalInsured.map((item) => ({ value: item, label: item }))