export const brokerName = [
    "Louis Campisano Jr",
    "Louis Yontef",
    "Jennifer Holmes",
    "Doris Donohue - Perosi",
    "Holly Heenan",
    "Cindy Bernd",
    "Michael Cluett",
    "Kristin Losordo",
    "Cecilia Loera",
    "Elsa Harrison",
    "Jim Galassi",
    "Ana Gomez",
    "Stephanie Flores",
    "Shawn Gu",
    "Leila Wang",
    "Deborah Verduci",
    "Natan Davydov",
    "Chris Mahlberg",
    "Grace Correa",
    "Frank Scotto",
    "Angela Chmelicek",
    "Artur Momjyan",
    "Heather Dezayas",
    "Carolina Morales",
    "Katy Batista",
    "Horace Chambers",
    "Nate Williams"
];

export const brokerOptions = brokerName.map((item) => ({ value: item, label: item }))