export const payment = [
    'null',
    'FULLPAY_POL',
    '25% Deposit Plus 1 Monthly Installment-$15 FEE',
    '40% Deposit Plus 2 Monthly Installments-$15 FEE',
    '25% Deposit Plus 8 Monthly Installments-$15 FEE',
    '25% Deposit Plus 7 Monthly Installments-$15 FEE',
    '20% Deposit Plus 9 Monthly Installments-$15 FEE',
    '20% Deposit Plus 8 Monthly Installments-$15 FEE',
    '20% Deposit Plus 9 Monthly Installments-$50 FEE',
    '10% Deposit Plus 9 Monthly Installments-$15 FEE',
    '15% Deposit Plus 9 Monthly Installments-$15 FEE',
    '15% Deposit Plus 8 Monthly Installments-$15 FEE',
    '12% Deposit Plus 8 Monthly Installments-$15 FEE',
    '10% Deposit Plus 10 Monthly Installments-$15 FEE',
    '25% Deposit Plus 10 Monthly Installments-$25 FEE',
    '25% Deposit Plus 9 Monthly Installments-$50 FEE',
    '20% Deposit Plus 8 Monthly Installments-$50 FEE',
    '15% Deposit Plus 10 Monthly Installments-$50 FEE',
    '10% Deposit Plus 7 Monthly Installments-$15 FEE',
    '25% Deposit Plus 1 Monthly Installments-$10 FEE',
    '40% Deposit Plus 2 Monthly Installments-$10 FEE',
    '25% Deposit Plus 8 Monthly Installments-$10 FEE',
    '25% Deposit Plus 9 Monthly Installments-$10 FEE',
    '20% Deposit Plus 9 Monthly Installments-$10 FEE',
    '10% Deposit Plus 9 Monthly Installments-$10 FEE',
    '15% Deposit Plus 9 Monthly Installments-$10 FEE',
    '15% Deposit Plus 10 Monthly Installments-$15 FEE',
    '10% Deposit Plus 10 Monthly Installments-$10 FEE',
    '8.33% Deposit Plus 11 Monthly Installments-$10 FEE'
]

export default payment.map((item) => ({ value: item, label: item }))
