export const urls = {
    getAllPoliciesUrl: 'https://policy-api-dot-delta-pagoda-337917.ue.r.appspot.com/policies/',
    createPoliciesUrl: 'https://policy-api-dot-delta-pagoda-337917.ue.r.appspot.com/policies/',
    getPolicy: (id) => `https://policy-api-dot-delta-pagoda-337917.ue.r.appspot.com/policies/${id}/`,
    updatePolicy: (id) => `https://policy-api-dot-delta-pagoda-337917.ue.r.appspot.com/policies/${id}/`,
  };


  export const testPolicies = [
    {
        "insured": {
            "zipCode": null,
            "contactName": null,
            "state": null,
            "firstName": null,
            "licenseEff": [
                null
            ],
            "suffix": null,
            "licenseNumber": null,
            "taxIdNumber": null,
            "email": null,
            "ssn": null,
            "licenseExp": null,
            "middleName": null,
            "contactEmail": null,
            "entity": null,
            "lastName": null,
            "corporationName": null,
            "city": null,
            "address1": null,
            "phoneNumber": null,
            "address2": null,
            "agent": null,
            "dob": null,
            "contactNumber": null,
            "licenseState": null,
            "isAddActive": false,
            "gender": null
        },
        "drivers": {
            "values": [
                {
                    "licenseExpDate": null,
                    "driverName": null,
                    "licenseNumber": null,
                    "licenseEffDate": null,
                    "states": null
                }
            ],
            "defaults": {
                "licenseEffDate": null,
                "states": null,
                "licenseExpDate": null,
                "licenseNumber": null,
                "driverName": null
            }
        },
        "loss_history": null,
        "created_at": 1650414436.24517,
        "policy": {
            "effectiveDate": null,
            "sizeClass": null,
            "expirationDate": null,
            "underwritingCode": null,
            "classCode": null,
            "classification": null,
            "lineOfBusiness": null,
            "states": null,
            "policyCategory": null,
            "policyLineItem": null,
            "businessUseClass": null,
            "radius": null,
            "coverageTerm": null,
            "agent": null
        },
        "documents": {},
        "coverage": {
            "csl": null,
            "cslSplitAuto": null,
            "unMotoristBodyPerAccident": null,
            "pIProtectionSplitBodyPerPerson": null,
            "deductable": null,
            "medicalSingleEntry": null,
            "nonCslSingleAuto": null,
            "medicalSplitBodyPerPerson": null,
            "medicalPayments": null,
            "underMotoristBodyPerAccident": null,
            "cslSingleLimit": null,
            "splitSectionAutoEntryOptions": null,
            "nonCslProperty": null,
            "pIProtectionSplitBodyPerAccident": null,
            "splitSectionBodyPerPerson": null,
            "medicalSplitAutoEntry": null,
            "nonCslSingleLimit": null,
            "uninsuredMotoristSingleLimit": null,
            "splitSectionBodyPerAccidentOptions": null,
            "nonOwnedCSL": null,
            "uninsuredMotoristSingleAutoEntry": null,
            "deductableAmount": null,
            "underMotoristAuto": null,
            "cslSingleAuto": null,
            "underMotoristBodyPerPerson": null,
            "splitSectionPropertyDamageOptions": null,
            "personalInjury": null,
            "medicalSingleLimit": null,
            "deductableAutoEntry": null,
            "underinsuredMotorist": null,
            "combinedSectionLimit": null,
            "unMotoristProperty": null,
            "underMotoristProperty": null,
            "unMotoristAuto": null,
            "pIProtectionSplitPropertyDamage": null,
            "combinedSectionEntry": null,
            "nonCslSplitAuto": null,
            "unMotoristBodyPerPerson": null,
            "cslBodyPerPerson": null,
            "medicalSplitPropertyDamage": null,
            "cslProperty": null,
            "overall": null,
            "underinsuredMotoristSingleAutoEntry": null,
            "pIProtectionSingleLimit": null,
            "errors": [],
            "pIProtectionSplitAutoEntry": null,
            "medicalSplitBodyPerAccident": null,
            "pIProtectionSingleEntry": null,
            "uninsuredMotorist": null,
            "underinsuredMotoristSingleLimit": null,
            "cslBodyPerAccident": null,
            "nonCslBodyPerPerson": null,
            "nonCslBodyPerAccident": null
        },
        "id": "90b6c796-5d7d-4417-a2b5-b7ee725a639e"
    }
];